## App Properties
#app.jwtSecret= JWTSuperSecretKey
#app.jwtExpirationInMs = 604800000

#spring.jpa.hibernate.ddl-auto = create-drop

#spring.jpa.properties.hibernate.show_sql=true

oauth:
  client-id: sticket_id
  client-secret: sticket_secret

jwt:
  jk-path: sticket_server.jks
  jk-password: 1q2w3e4r!@#
  key-alias: server_private
  key-password: 1q2w3e4r!@#

---
spring:
  profiles:
#    active: prod
    active: dev
---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sticket
    password: 1q2w3e4r!@#
    driver-class-name: org.h2.Driver
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://sticket.cmnxncxddliv.ap-northeast-2.rds.amazonaws.com:3306/sticket?useUnicode=yes&characterEncoding=utf-8
    username: sticket
    password: 1q2w3e4r!
    driver-class-name: org.mariadb.jdbc.Driver